version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Europe/Moscow
    versioning-strategy: increase
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      fastify:
        patterns:
          - "@fastify/*"
          - "fastify*"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "typescript-eslint"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Europe/Moscow
    labels:
      - ci
    commit-message:
      prefix: ci
