'use client';
import './arena.css';
import { useEffect, useRef, useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { useParams, useRouter } from 'next/navigation';
import { api } from '@/lib/api';
import { useAuth } from '@/lib/auth';
import type { DebateTurn } from '@/types';

const phaseNames = ['Позиция', 'Вопрос', 'Ответ', 'Ballot'];
const skillLabels: Record<string, string> = { STRUCTURE: 'Структура', CONTENT: 'Доказательства', REFUTATION: 'Опровержение', LOGIC: 'Логика', DELIVERY: 'Подача' };
const kindLabels: Record<string, string> = { OPENING: 'позиция', REBUTTAL: 'ответ оппонента', QUESTION: 'вопрос', RESPONSE: 'ответ', CLOSING: 'финал' };
function phaseFor(status: string, exchanges: number) { if (status === 'AWAITING_JUDGE' || status === 'COMPLETED') return 3; return Math.min(exchanges, 2); }
function formatTime(seconds: number) { return `${Math.floor(seconds / 60).toString().padStart(2, '0')}:${(seconds % 60).toString().padStart(2, '0')}`; }

export default function DebatePage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const { user, loading } = useAuth();
  const [text, setText] = useState(''); const [error, setError] = useState(''); const [recording, setRecording] = useState(false); const [seconds, setSeconds] = useState(180);
  const recorderRef = useRef<MediaRecorder | null>(null); const bottomRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!loading && !user) router.push('/auth/login'); }, [loading, user, router]);
  useEffect(() => { const timer = window.setInterval(() => setSeconds((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, []);
  const { data: round, refetch, isLoading } = useQuery({ queryKey: ['round', id], queryFn: () => api.getRound(id), enabled: Boolean(user), refetchInterval: 3000 });
  const turns = (round?.turns ?? []) as DebateTurn[]; const phase = round ? phaseFor(round.status, round.exchangesDone) : 0; const latestOpponent = [...turns].reverse().find((turn) => turn.role === 'OPPONENT'); const latestQuestion = latestOpponent?.question ?? null; const isWaiting = round?.status === 'AWAITING_JUDGE'; const isFinished = round?.status === 'COMPLETED' || round?.status === 'ABORTED'; const currentSkill = round?.focusSkill ? skillLabels[round.focusSkill] : 'точность ответа'; const responseHint = latestQuestion ?? (turns.length ? 'Сформулируй ответ своими словами' : 'Сделай первый ход: заяви главный аргумент');
  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [turns.length]);
  const turnMutation = useMutation({ mutationFn: (value: string) => api.submitTurn(id, { text: value }), onSuccess: () => { setText(''); setError(''); refetch(); setSeconds(180); }, onError: (err) => setError(err instanceof Error ? err.message : 'Не удалось отправить реплику') });
  const judgeMutation = useMutation({ mutationFn: () => api.judgeRound(id), onSuccess: () => router.push(`/rounds/${id}/results`), onError: (err) => setError(err instanceof Error ? err.message : 'Судья не ответил. Попробуй ещё раз.') });
  const abortMutation = useMutation({ mutationFn: () => api.abortRound(id), onSuccess: () => router.push('/topics') });
  async function toggleRecording() { if (recording) { recorderRef.current?.stop(); setRecording(false); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const recorder = new MediaRecorder(stream); const chunks: Blob[] = []; recorder.ondataavailable = (event) => { if (event.data.size) chunks.push(event.data); }; recorder.onstop = async () => { stream.getTracks().forEach((track) => track.stop()); try { const result = await api.uploadAudio(new Blob(chunks, { type: 'audio/webm' })); setText((value) => value ? `${value} ${result.text}` : result.text); } catch { setError('Не удалось распознать голос. Напиши ответ вручную.'); } }; recorder.start(); recorderRef.current = recorder; setRecording(true); setError(''); } catch { setError('Нет доступа к микрофону. Можно ответить текстом.'); } }
  function submit(event: React.FormEvent) { event.preventDefault(); if (!text.trim() || turnMutation.isPending || isWaiting) return; turnMutation.mutate(text.trim()); }
  if (loading || isLoading) return <div className="arena-loading"><div className="arena-loading-bar"/><div className="arena-loading-stage"/><div className="arena-loading-bar short"/></div>;
  if (!user || !round) return null;
  const side = round.stance === 'PRO' ? 'ЗА' : 'ПРОТИВ'; const completed = round.status === 'COMPLETED'; const exchangeLabel = `${Math.min(round.exchangesDone + 1, 3)} / 3`;
  return <main className="arena-page">
    <header className="arena-topbar"><button className="arena-brand" onClick={() => router.push('/topics')}><span className="arena-brand-mark">T</span><span>talqyla</span></button><nav className="arena-nav"><span className="active">Раунд</span><span>Тренировки</span><span>Прогресс</span></nav><div className="arena-user"><span>{user.name.split(' ')[0]}</span><span className="arena-avatar">{user.name.slice(0, 1).toUpperCase()}</span></div></header>
    <div className="arena-shell">
      <aside className="arena-left"><section className="arena-panel arena-context"><div className="arena-kicker">Контекст</div><h2>{side} по теме</h2><p>Ты защищаешь одну позицию. Оппонент будет проверять её по шагам, не пытайся выиграть весь спор сразу.</p><div className={`stance-chip ${round.stance === 'PRO' ? 'pro' : 'con'}`}><span/> Позиция: {side}</div></section><section className="arena-panel arena-rounds"><div className="arena-kicker">Ход раунда</div>{phaseNames.slice(0, 3).map((name, index) => <div className={`arena-round-row ${index < phase ? 'done' : ''} ${index === phase ? 'current' : ''}`} key={name}><b>{index < phase ? '✓' : index + 1}</b><span>{name}</span><small>{index < phase ? 'готово' : index === phase ? 'сейчас' : 'дальше'}</small></div>)}<div className="arena-round-row locked"><b>4</b><span>Ballot</span><small>после раунда</small></div></section><section className="arena-panel arena-tactic"><div className="arena-kicker">Фокус</div><strong>{currentSkill}</strong><p>Один навык за раз. Так прогресс не растворяется в красивых словах.</p></section></aside>
      <section className="arena-stage"><div className="arena-stage-head"><div><div className="arena-kicker">Structured sparring</div><h1>Раунд {exchangeLabel}</h1></div><div className="arena-stage-meta"><span className="live-dot"/> {completed ? 'завершён' : 'в процессе'}</div></div><div className="arena-progress"><span style={{ width: `${Math.max(8, (phase / 3) * 100)}%` }}/></div><div className="arena-motion"><div className="arena-kicker">Дебатная резолюция</div><h2>{round.topic?.title}</h2><p>Сначала ответь на конкретный вопрос, потом добавь причину и последствие.</p><div className="arena-motion-footer"><span>Твоя сторона: <b>{side}</b></span><span>3 коротких обмена</span></div></div><div className="arena-clock"><span>{formatTime(seconds)}</span><small>время на ответ</small></div>
        <div className="arena-scene"><div className="arena-lane opponent-lane"><span className="lane-label">ОППОНЕНТ</span><div className="lane-avatar opponent">A</div><strong>AI-оппонент</strong><small>ищет слабое место</small></div><div className="arena-turns">{turns.length === 0 && <div className="arena-empty"><span className="empty-orb">+</span><strong>Первый ход за тобой</strong><p>Позиция уже собрана. Теперь объясни её так, чтобы оппоненту было за что зацепиться.</p></div>}{turns.map((turn) => <article className={`arena-turn ${turn.role === 'STUDENT' ? 'student' : 'opponent'}`} key={turn.id}><div className="turn-label"><span className={turn.role === 'STUDENT' ? 'student-dot' : 'opponent-dot'}/>{turn.role === 'STUDENT' ? 'ТЫ' : 'ОППОНЕНТ'}<small>{kindLabels[turn.kind] ?? 'реплика'}</small></div><p>{turn.contentText}</p>{turn.question && <div className="arena-question"><span>?</span><div><small>ответь на это</small><b>{turn.question}</b></div></div>}</article>)}<div ref={bottomRef}/></div><div className="arena-lane student-lane"><span className="lane-label">ТВОЯ СТОРОНА</span><div className="lane-avatar student">{user.name.slice(0, 1).toUpperCase()}</div><strong>{user.name.split(' ')[0]}</strong><small>{side}</small></div></div>
        {!isFinished && !isWaiting && <form className="arena-composer" onSubmit={submit}><div className="composer-heading"><span>ТВОЙ ХОД</span><b>{responseHint}</b></div><textarea value={text} onChange={(event) => setText(event.target.value)} placeholder="Напиши ответ здесь..." maxLength={2000} disabled={turnMutation.isPending}/><div className="composer-actions"><span>{text.length} / 2000</span><button type="button" className={`record-button ${recording ? 'recording' : ''}`} onClick={toggleRecording}>{recording ? 'Остановить' : 'Голосом'}</button><button className="arena-submit" type="submit" disabled={!text.trim() || turnMutation.isPending}>{turnMutation.isPending ? 'Оппонент думает...' : 'Ответить  →'}</button></div></form>}{isWaiting && <div className="arena-verdict"><div><span className="arena-kicker">Три обмена завершены</span><strong>Готов увидеть, что сработало?</strong></div><button className="arena-submit" onClick={() => judgeMutation.mutate()} disabled={judgeMutation.isPending}>{judgeMutation.isPending ? 'Судья разбирает...' : 'Открыть ballot  →'}</button></div>}{error && <div className="arena-error">{error}</div>}</section>
      <aside className="arena-right"><section className="arena-panel judge-panel"><div className="judge-tabs"><span className="active">Фокус</span><span>Оценка</span></div><div className="arena-kicker">Пока раунд идёт</div><h2>{currentSkill}</h2><div className="focus-ring"><span>{phase + 1}</span><small>этап</small></div><p>{isWaiting ? 'Раунд закончен. Открой ballot, чтобы получить оценки и следующий drill.' : 'Оценки появятся после трёх обменов. Сейчас важнее один хороший ответ.'}</p></section><section className="arena-panel judge-feedback"><div className="arena-kicker">Правило ответа</div><ol><li>Назови, с чем споришь.</li><li>Дай причину или пример.</li><li>Покажи, почему это меняет вывод.</li></ol></section><button className="arena-withdraw" onClick={() => abortMutation.mutate()} disabled={abortMutation.isPending || isFinished}>Выйти из раунда</button></aside>
    </div>
  </main>;
}
