import http from 'node:http';
import { randomUUID, timingSafeEqual } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { join, extname } from 'node:path';
import { routedChat, configuredProviderNames } from './ai/router.js';
import { transcribeAudio } from './ai/stt.js';

type Language='ru'|'kk';
type Criterion={score:number;quote:string|null;reason:string};
type MoveResult={criteria:Record<string,Criterion>;observation:string;advice:string;quote:string|null;nextQuestion:string;provider:string;model?:string};
type Session={sessionId:string;language:Language;targetSkill:string;topic:string;userPosition:string;aiPosition:string;round:number;maxRounds:number;messages:any[];judgeResults:MoveResult[];status:string;aiProviders:string[];coachNote?:{observation:string;advice:string;quote:string|null};feedback?:any};
const sessions=new Map<string,Session>();
const criterionNames=['directness','reasoning','rebuttal','structure'] as const;
const criterionLabels={ru:{directness:'Прямой ответ',reasoning:'Обоснование',rebuttal:'Работа с возражением',structure:'Структура'},kk:{directness:'Тікелей жауап',reasoning:'Негіздеу',rebuttal:'Қарсылықпен жұмыс',structure:'Құрылым'}};
const fallbackCases={ru:[{topic:'Следует ли школам ограничивать использование ИИ в домашних заданиях?',userPosition:'Школы должны обучать ответственному использованию ИИ, а не полностью запрещать его.',aiPosition:'Школы должны ограничивать ИИ, потому что он мешает самостоятельному обучению.',openingQuestion:'Если ученик может получить готовый ответ от ИИ, как учитель поймёт, что ученик действительно разобрался в теме?'},{topic:'Нужно ли ограничивать социальные сети для подростков?',userPosition:'Подросткам нужны обучение и поддержка, а не жёсткий запрет.',aiPosition:'Подросткам нужны ограничения, потому что платформы специально удерживают внимание.',openingQuestion:'Если платформы создаются для удержания внимания, почему одной силы воли подростка должно быть достаточно?'}],kk:[{topic:'Мектептер үй тапсырмасында жасанды интеллектіні пайдалануды шектеуі керек пе?',userPosition:'Мектептер жасанды интеллектіні толық тыймай, оны жауапкершілікпен қолдануды үйретуі керек.',aiPosition:'Мектептер жасанды интеллектіні шектеуі керек, себебі ол өз бетінше оқуға кедергі келтіреді.',openingQuestion:'Оқушы дайын жауапты жасанды интеллектіден алса, мұғалім оның тақырыпты шынымен түсінгенін қалай біледі?'},{topic:'Жасөспірімдерге әлеуметтік желі бойынша шектеу қажет пе?',userPosition:'Жасөспірімдерге қатаң тыйым емес, білім мен қолдау қажет.',aiPosition:'Платформалар назарды ұстап тұру үшін жасалғандықтан, шектеу қажет.',openingQuestion:'Платформалар назарды ұстап тұру үшін жасалса, неге жасөспірімнің ерік-жігері жеткілікті деп ойлауымыз керек?'}]};
const jsonFrom=(text:string)=>{try{return JSON.parse(String(text||'').replace(/^```json\s*|```$/g,'').trim())}catch{return null}};
const lastAi=(s:Session)=>[...s.messages].reverse().find(m=>m.speaker==='ai')?.text||'';
const studentTexts=(s:Session)=>s.messages.filter(m=>m.speaker==='user').map(m=>String(m.text));
const exactQuote=(quote:any,texts:string[])=>typeof quote==='string'&&quote.trim().length>=4&&texts.some(t=>t.includes(quote.trim()))?quote.trim():null;
const wrongLanguage=(text:any,language:Language)=>language==='ru'&&(String(text||'').match(/\b[A-Za-z]{3,}\b/g)||[]).length>1;
const local=(s:Session,ru:string,kk:string)=>s.language==='kk'?kk:ru;
const safeLocalized=(value:any,s:Session,fallback:string)=>typeof value==='string'&&value.trim()&&!wrongLanguage(value,s.language)?value.trim():fallback;

async function createSession(language:Language,targetSkill:string):Promise<Session>{
 const lang=language==='kk'?'только на казахском языке':'только на русском языке';
 const ai=await routedChat({responseFormat:'json_object',temperature:.5,maxTokens:450,messages:[{role:'system',content:`Создай учебный кейс для школьных дебатов. Пиши ${lang}, без английских фраз. Не придумывай никаких фактов об ученике. Верни только JSON: {"topic":"...","userPosition":"...","aiPosition":"...","openingQuestion":"..."}. Тема понятна без специальных знаний.`},{role:'user',content:`Тренируемый навык: ${targetSkill}. Создай новый кейс.`}]});
 const parsed=jsonFrom(ai.text);const fallback=fallbackCases[language][Math.floor(Math.random()*fallbackCases[language].length)]!;
 const valid=parsed&&['topic','userPosition','aiPosition','openingQuestion'].every(k=>typeof parsed[k]==='string'&&parsed[k].trim()&&!wrongLanguage(parsed[k],language));const c=valid?parsed:fallback;
 const s:Session={sessionId:randomUUID(),language,targetSkill,topic:c.topic,userPosition:c.userPosition,aiPosition:c.aiPosition,round:1,maxRounds:4,messages:[{id:randomUUID(),speaker:'ai',text:c.openingQuestion,round:1}],judgeResults:[],status:'active',aiProviders:[ai.provider]};sessions.set(s.sessionId,s);return s;
}
function validateMove(parsed:any,s:Session,answer:string,provider:string,model?:string):MoveResult{
 const used=new Set<string>();const criteria:Record<string,Criterion>={};
 for(const name of criterionNames){const source=parsed?.criteria?.[name]||{};const quote=exactQuote(source.quote,[answer]);const duplicate=quote?used.has(quote):false;if(quote&&!duplicate)used.add(quote);const score=quote&&!duplicate?Math.max(0,Math.min(5,Math.round(Number(source.score)||0))):0;criteria[name]={score,quote:score>0?quote:null,reason:safeLocalized(source.reason,s,score>0?local(s,'Оценка подтверждена цитатой из ответа.','Баға жауаптан алынған дәйексөзбен расталды.'):local(s,'Балл не начислен: нет отдельной подтверждённой цитаты.','Ұпай берілмеді: бөлек расталған дәйексөз жоқ.'))}}
 const ranked=Object.values(criteria).filter(c=>c.quote).sort((a,b)=>b.score-a.score);const evidence=ranked[0]?.quote||exactQuote(answer,[answer]);
 return{criteria,quote:evidence,observation:safeLocalized(parsed?.observation,s,local(s,'Комментарий основан на последнем ответе.','Пікір соңғы жауапқа негізделген.')),advice:safeLocalized(parsed?.advice,s,local(s,'Сначала прямо ответьте на возражение, затем объясните причинную связь.','Алдымен қарсылыққа тікелей жауап беріп, кейін себептік байланысты түсіндіріңіз.')),nextQuestion:safeLocalized(parsed?.nextQuestion,s,local(s,'Как ваш аргумент отвечает именно на последнее возражение?','Сіздің дәлеліңіз соңғы қарсылыққа нақты қалай жауап береді?')),provider,model};
}
async function judgeMove(s:Session,answer:string):Promise<MoveResult>{
 const lang=s.language==='kk'?'ИСКЛЮЧИТЕЛЬНО НА КАЗАХСКОМ ЯЗЫКЕ':'ИСКЛЮЧИТЕЛЬНО НА РУССКОМ ЯЗЫКЕ';
 const ai=await routedChat({responseFormat:'json_object',temperature:.1,maxTokens:1000,messages:[{role:'system',content:`Ты строгий, но полезный судья школьных дебатов. Пиши ${lang}; ни одного английского предложения. Анализируй только данный ответ, не придумывай факты об ученике. Оцени 4 критерия от 0 до 5: directness — прямой ответ на вопрос; reasoning — объяснена причинная связь; rebuttal — разобрано возражение оппонента; structure — тезис и объяснение логично связаны. ЛЮБОЙ положительный балл обязан иметь отдельную дословную цитату из ответа. Не исправляй и не перефразируй цитату. Не используй одну цитату для двух критериев. Верни только JSON: {"criteria":{"directness":{"score":0,"quote":null,"reason":"почему"},"reasoning":{...},"rebuttal":{...},"structure":{...}},"observation":"одно краткое замечание о последнем ответе","advice":"один конкретный совет для следующего ответа","nextQuestion":"один следующий вопрос оппонента, основанный на слабом месте ответа"}.`},{role:'user',content:`Тема: ${s.topic}\nПозиция ученика: ${s.userPosition}\nПозиция оппонента: ${s.aiPosition}\nПоследний вопрос оппонента: ${lastAi(s)}\nДословный ответ ученика: ${answer}`}]});
 return validateMove(jsonFrom(ai.text),s,answer,ai.provider,ai.model);
}
function verifiedCards(items:any,s:Session,limit:number){const texts=studentTexts(s),used=new Set<string>(),out:any[]=[];for(const item of Array.isArray(items)?items:[]){const quote=exactQuote(item?.quote,texts);if(!quote||used.has(quote)||wrongLanguage(item?.explanation,s.language))continue;used.add(quote);out.push({quote,explanation:String(item.explanation||'').trim(),action:safeLocalized(item.action,s,'')});if(out.length>=limit)break}return out}
function criterionSummary(s:Session){return criterionNames.map(name=>{const points=s.judgeResults.reduce((sum,r)=>sum+(r.criteria[name]?.score||0),0);return{key:name,label:criterionLabels[s.language][name],points,maxPoints:s.maxRounds*5,percent:Math.round(points/(s.maxRounds*5)*100)}})}
async function buildFinalFeedback(s:Session){
 const transcript=s.messages.map(m=>`${m.speaker==='user'?'УЧЕНИК':'ОППОНЕНТ'} (раунд ${m.round}): ${m.text}`).join('\n');const lang=s.language==='kk'?'ИСКЛЮЧИТЕЛЬНО НА КАЗАХСКОМ ЯЗЫКЕ':'ИСКЛЮЧИТЕЛЬНО НА РУССКОМ ЯЗЫКЕ';
 const ai=await routedChat({responseFormat:'json_object',temperature:.15,maxTokens:1600,messages:[{role:'system',content:`Ты финальный судья и тренер. Пиши ${lang}, без английского. Используй только стенограмму. Не придумывай сведения об ученике. Каждое утверждение о качестве ответа должно сопровождаться ДОСЛОВНОЙ цитатой ученика. Дай детальный, практичный разбор. Верни JSON: {"summary":"2-3 предложения об итоговом качестве аргументации","strengths":[{"quote":"дословная цитата","explanation":"что конкретно сработало и почему","action":"как повторять это дальше"}],"improvements":[{"quote":"дословная цитата","explanation":"точная проблема и её влияние","action":"как переписать или усилить этот фрагмент"}],"plan":{"focus":"один главный навык следующей тренировки","why":"почему он выбран на основе ответов","exercises":["конкретное упражнение 1","конкретное упражнение 2","конкретное упражнение 3"]}}. В strengths и improvements используй разные цитаты.`},{role:'user',content:`Тема: ${s.topic}\nЦелевой навык: ${s.targetSkill}\nСТЕНОГРАММА:\n${transcript}\nПроверенные баллы по критериям:\n${JSON.stringify(criterionSummary(s))}`}]});
 const parsed=jsonFrom(ai.text)||{};let strengths=verifiedCards(parsed.strengths,s,3);let improvements=verifiedCards(parsed.improvements,s,3);const used=new Set(strengths.map(x=>x.quote));improvements=improvements.filter(x=>!used.has(x.quote));
 const allCriteria=s.judgeResults.flatMap(r=>Object.values(r.criteria)).filter(c=>c.quote);if(!strengths.length){const best=[...allCriteria].sort((a,b)=>b.score-a.score)[0];if(best)strengths=[{quote:best.quote,explanation:best.reason,action:local(s,'Сохраните такую связку тезиса и объяснения.','Тезис пен түсіндірудің осындай байланысын сақтаңыз.')}]}if(!improvements.length){const weak=[...allCriteria].filter(c=>!used.has(c.quote)).sort((a,b)=>a.score-b.score)[0];if(weak)improvements=[{quote:weak.quote,explanation:weak.reason,action:local(s,'Перепишите фрагмент: сначала ответ на возражение, затем причина и пример.','Бөлікті қайта жазыңыз: алдымен қарсылыққа жауап, кейін себеп пен мысал.')}]}const raw=s.judgeResults.reduce((sum,r)=>sum+Object.values(r.criteria).reduce((a,c)=>a+c.score,0),0),max=s.maxRounds*criterionNames.length*5;
 const defaultPlan={focus:s.targetSkill,why:local(s,'Этот навык выбран по результатам проверенной рубрики текущего раунда.','Бұл дағды ағымдағы раундтың тексерілген рубрикасы бойынша таңдалды.'),exercises:[local(s,'Дайте прямой ответ одним предложением.','Бір сөйлеммен тікелей жауап беріңіз.'),local(s,'Добавьте причинную связку «потому что → поэтому».','«Себебі → сондықтан» себептік байланысын қосыңыз.'),local(s,'Ответьте на конкретное возражение и приведите один пример.','Нақты қарсылыққа жауап беріп, бір мысал келтіріңіз.')]};const p=parsed.plan||{};const exercises=Array.isArray(p.exercises)?p.exercises.filter((x:any)=>typeof x==='string'&&x.trim()&&!wrongLanguage(x,s.language)).slice(0,3):[];
 return{score:Math.round(raw/max*100),earnedPoints:raw,maxPoints:max,scoreExplanation:local(s,`Итог: ${raw} из ${max} подтверждённых баллов по рубрике. Баллы без проверенной цитаты не засчитывались.`,`Қорытынды: рубрика бойынша расталған ${raw}/${max} ұпай. Тексерілген дәйексөзсіз ұпай есептелмеді.`),criteria:criterionSummary(s),summary:safeLocalized(parsed.summary,s,local(s,'Разбор построен только на ответах этого раунда.','Талдау тек осы раундтағы жауаптарға негізделген.')),strengths,improvements,plan:{focus:safeLocalized(p.focus,s,defaultPlan.focus),why:safeLocalized(p.why,s,defaultPlan.why),exercises:exercises.length?exercises:defaultPlan.exercises},provider:[...new Set([...s.aiProviders,ai.provider])].filter(x=>x!=='mock')};
}
async function answerSession(id:string,text:string):Promise<Session>{
 const s=sessions.get(id);if(!s)throw Error('Session not found');if(s.status!=='active')throw Error('Session finished');const clean=String(text||'').trim();if(!clean)throw Error('Empty response');s.messages.push({id:randomUUID(),speaker:'user',text:clean,round:s.round});const judged=await judgeMove(s,clean);s.judgeResults.push(judged);s.aiProviders.push(judged.provider);s.coachNote={observation:judged.observation,advice:judged.advice,quote:judged.quote};if(s.round>=s.maxRounds){s.status='finished';s.feedback=await buildFinalFeedback(s);return s}s.round++;s.messages.push({id:randomUUID(),speaker:'ai',text:judged.nextQuestion,round:s.round});return s;
}
const token=process.env.TELEGRAM_BOT_TOKEN||'',secret=process.env.TELEGRAM_WEBHOOK_SECRET||'',domain=process.env.RAILWAY_PUBLIC_DOMAIN;const publicUrl=process.env.TELEGRAM_WEBAPP_URL||process.env.PUBLIC_URL||(domain?'https://'+domain:'');const tg=(m:string)=>'https://api.telegram.org/bot'+token+'/'+m;async function telegram(m:string,p:any){const r=await fetch(tg(m),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(p)});if(!r.ok)throw Error(await r.text())}async function botUpdate(u:any){const chat=u?.message?.chat?.id;if(!chat)return;await telegram('sendMessage',{chat_id:chat,text:'Откройте Talqyla и выберите язык.\nTalqyla қолданбасын ашып, тілді таңдаңыз.',reply_markup:publicUrl?{inline_keyboard:[[{text:'Открыть / Ашу',web_app:{url:publicUrl}}]]}:undefined})}function equal(a:string,b:string){const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y)}const mime:any={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};async function staticFile(url:string,res:any){const clean=url.split('?')[0]||'/';const path=clean==='/'?'/index.html':clean;try{const data=await readFile(join(process.cwd(),'miniapp',path.replace(/^\//,'')));res.setHeader('content-type',mime[extname(path)]||'application/octet-stream');res.end(data)}catch{res.statusCode=404;res.end('Not found')}}
export const server=http.createServer((req,res)=>{const chunks:Buffer[]=[];let size=0;req.on('data',c=>{size+=c.length;if(size<=12*1024*1024)chunks.push(Buffer.from(c))});req.on('end',async()=>{try{const raw=Buffer.concat(chunks);res.setHeader('cache-control','no-store');if(req.url==='/health')return res.end(JSON.stringify({ok:true,app:'Talqyla Mini App',providers:configuredProviderNames().map(x=>x.name),stt:Boolean(process.env.GROQ_API_KEY||process.env.DEEPGRAM_API_KEY)}));if(req.url==='/api/providers')return res.end(JSON.stringify({llm:configuredProviderNames(),stt:{groq:Boolean(process.env.GROQ_API_KEY),deepgram:Boolean(process.env.DEEPGRAM_API_KEY)}}));if(req.url==='/api/stt'&&req.method==='POST'){if(size>12*1024*1024)throw Error('Audio too large');const out=await transcribeAudio(raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.byteLength),String(req.headers['content-type']||'audio/webm'));res.setHeader('content-type','application/json');return res.end(JSON.stringify(out))}if(req.url==='/telegram/webhook'&&req.method==='POST'){if(secret&&!equal(String(req.headers['x-telegram-bot-api-secret-token']||''),secret)){res.statusCode=401;return res.end()}await botUpdate(JSON.parse(raw.toString()||'{}'));return res.end(JSON.stringify({ok:true}))}if(req.url==='/api/debate/start'&&req.method==='POST'){const b=JSON.parse(raw.toString()||'{}');const language:Language=b.language==='kk'?'kk':'ru';res.setHeader('content-type','application/json');return res.end(JSON.stringify(await createSession(language,String(b.skill||(language==='kk'?'Теріске шығару':'Опровержение')))))}if(req.url?.startsWith('/api/debate/')&&req.url.endsWith('/respond')){const id=req.url.split('/')[3]!;const b=JSON.parse(raw.toString()||'{}');res.setHeader('content-type','application/json');return res.end(JSON.stringify(await answerSession(id,b.text)))}return staticFile(req.url||'/',res)}catch(e:any){res.statusCode=400;res.setHeader('content-type','application/json');res.end(JSON.stringify({error:e.message}))}})});const port=Number(process.env.PORT||8787);server.listen(port,'0.0.0.0',async()=>{console.log('Talqyla Mini App listening on '+port);console.log('LLM providers:',configuredProviderNames());console.log('STT:',{groq:Boolean(process.env.GROQ_API_KEY),deepgram:Boolean(process.env.DEEPGRAM_API_KEY)});if(token&&publicUrl){const p:any={url:publicUrl.replace(/\/$/,'')+'/telegram/webhook',allowed_updates:['message']};if(secret)p.secret_token=secret;try{await telegram('setWebhook',p);console.log('Telegram Mini App webhook configured: '+publicUrl)}catch(e){console.error('Webhook setup failed',e)}}});
